
services:
  app:
    build: .
    container_name: form-management-app
    ports:
      - "5005:5000"
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_HOSTNAME=${MONGODB_HOSTNAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - form_management_net

  mongo:
    image: mongo:latest
    container_name: form-management-mongo
    restart: unless-stopped
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - form_management_net

volumes:
  mongo_data:
    driver: local

networks:
  form_management_net:
    driver: bridge