services:
  web:
    build: .
    ports:
    - "5000:5000" 
    volumes:
    - .:/code
    depends_on:
    - db
  db:
    image: mysql:5.
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my-db
      - MYSQL_USER=my-user
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
      - MYSQL_INITDB_SKIP_TZINFO=yes
      - MYSQL_INITDB_SKIP_DBS=mysql
  