openapi: "3.0.0"
info:
  title: "Form Management API"
  description: "API for managing forms and submitting responses."
  version: "1.0.0"
servers:
  - url: "http://localhost:5005"
paths:
  /forms:
    post:
      summary: "Create a new form"
      requestBody:
        description: "Form data to create"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                fields:
                  type: array
                  items:
                    type: object
                    properties:
                      label:
                        type: string
                      type:
                        type: string
                      is_required:
                        type: boolean
      responses:
        201:
          description: "Form created"
        400:
          description: "Validation error"
    get:
      summary: "Get all forms"
      responses:
        200:
          description: "List of forms"
